name: Dew of your Youth
markdown: kramdown
highlighter: rouge
linenos: tru
permalink: /:categories/:year/:month/:day/:title:output_ext
title: Dew of your Youth
description: Yaakov Shore rambles on about life, tech, coding and banjo licks.
author: Yaakov Shore
url: https://dewofyouryouth.github.io
feed_items: 10
paginate: 5
feed_update_period: daily
feed_update_frequency: 1
twitter:
  username: sergeantspam1
