name: Dew of your Youth
markdown: kramdown
highlighter: rouge
title: Dew of your Youth
description: Yaakov Shore rambles on about life, tech, coding and banjo licks.
author: Yaakov Shore
twitter:
  username: dewofyouryouth
